from src.controllers.ArchivoController import *
from src.controllers.ComunaController import *
from src.controllers.DenunciaController import *
from src.controllers.DenunciaMateriaController import *
from src.controllers.DireccionController import *
from src.controllers.EstadoDenunciaController import *
from src.controllers.ExcepcionesController import *
from src.controllers.IndexController import *
from src.controllers.MateriaController import *
from src.controllers.ParteController import *
from src.controllers.PersonaController import *
from src.controllers.RolController import *
from src.controllers.TipoArchivoController import *
from src.controllers.TipoDireccionController import *
from src.controllers.TipoParteController import *
from src.controllers.TipoPersonaController import *
from src.controllers.UsuarioController import *
